version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: minicarrot-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: minicarrot
      MYSQL_USER: minicarrot
      MYSQL_PASSWORD: password123
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # User Service 애플리케이션
  user-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: minicarrot-user-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 데이터베이스 설정
      DB_URL: jdbc:mysql://mysql:3306/minicarrot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      DB_USERNAME: minicarrot
      DB_PASSWORD: password123
      
      # JWT 설정
      JWT_SECRET: mini-carrot-super-secret-key-change-this-in-production-environment
      JWT_EXPIRATION: 86400000
      
      # JPA 설정
      JPA_DDL_AUTO: create-drop
      JPA_SHOW_SQL: false
      
      # 로깅 설정
      LOG_LEVEL: INFO
      LOG_LEVEL_SECURITY: WARN
      
      # 서버 설정
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/users/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: minicarrot-network 