server:
  port: 8080

spring:
  application:
    name: mini-carrot-user-service
  
  # 프로파일별 설정 파일 포함
  profiles:
    include: local
  
  # 데이터베이스 설정 (실제 값은 application-local.yml에서 관리)
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/minicarrot}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000
      leak-detection-threshold: 15000
      connection-test-query: SELECT 1
      validation-timeout: 2000
      auto-commit: false
      initialization-fail-timeout: 1
      keepalive-time: 120000
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    database: mysql

  # RabbitMQ 설정
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

# JWT 설정 (실제 값은 application-local.yml에서 관리)
jwt:
  secret: ${JWT_SECRET:default-secret-key-for-development-only}
  expiration: ${JWT_EXPIRATION:86400000}

# 로깅 설정
logging:
  level:
    com.minicarrot.user: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}

# 외부 서비스 연동 설정
app:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  external-api:
    timeout: ${EXTERNAL_API_TIMEOUT:5}


    
# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
